config/routes.rb
Rails.application.routes.draw do
    root 'sessions#new'   
    get '/', to: 'sessions#new'
    post '/', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/connection', to: 'connections#show'
    get '/connection/sas', to: 'connections#get_sas'
    get '/connection/configure', to: 'connections#configure'
    get '/connection/configure/:conn_name', to: 'connections#configure'
    get '/connection/history', to: 'connections#get_history'
    post '/connection/update', to: 'connections#update'
    get '/configuration', to: 'configurations#show'
    post '/configuration', to: 'configurations#update'
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController
    def show
        if not admin?
            redirect_to '/'
            return
        end
        @gate_url = 'https://localhost'
        @gate_token = 'default_token'
        @min_user_id = '5000'
        @user_groups = ''
        @conns = get_conns
        if ENV['USER_GROUPS']
            @user_groups = ENV['USER_GROUPS']
        end
        pam_config = File.read('/etc/pam.d/gate-sso')
        pam_config.split(' ').each do |data|
            if data.include? 'url='
                @gate_url = data[4..-1]
            elsif data.include? 'token='
                @gate_token = data[6..-1]
            elsif data.include? 'min_user_id='
                @min_user_id = data[12..-1]
            end
        end
    end
    def update
        if not admin?
            redirect_to '/'
            return
        end
        @gate_url = 'https://localhost'
        @gate_token = 'default_token'
        @min_user_id = '5000'

        if params[:configuration][:gate_url]
            @gate_url = params[:configuration][:gate_url]
        end
        if params[:configuration][:gate_token]
           @gate_token = params[:configuration][:gate_token]
        end
        if params[:configuration][:min_user_id]
            @min_user_id = params[:configuration][:min_user_id]
        end
        if params[:configuration][:pre_shared_key]
            @pre_shared_key = params[:configuration][:pre_shared_key]
        end
        if params[:configuration][:user_groups]
            ENV['USER_GROUPS'] = params[:configuration][:user_groups]
        end
        gate_sso = ERB.new(File.read('app/views/configurations/gate-sso.erb'))
        File.write('/etc/pam.d/gate-sso', gate_sso.result(binding))

        redirect_to '/configuration'
    end
end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/views/configurations/gate-sso.erb
auth sufficient pam_gate.so url=<%= @gate_url %> token=<%= @gate_token %> min_user_id=<%= @min_user_id %>
account sufficient pam_gate.so url=<%= @gate_url %> token=<%= @gate_token %> min_user_id=<%= @min_user_id %>

app/views/configurations/show.html.slim
nav.navbar.navbar-default
  div.container-fluid
    div.navbar-header
      a.navbar-brand Gojek VPN
    
    ul.nav.navbar-nav
      li
        = link_to "Connections", connection_path
      li
        = link_to "History", connection_history_path
      - if admin?
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown"
            | VPN Configuration
            span.caret
          ul.dropdown-menu role="menu"
            - @conns.each do |conn|
              li
                = link_to conn, '/connection/configure/'+conn
        li
          = link_to "Gate Configuration", configuration_path
    
    ul.nav.navbar-nav.navbar-right
      li
        = link_to "Log out", logout_path, :method => :delete

.row
  .col-md-6.col-md-offset-3
    = form_for(:configuration, url: '/configuration') do |f|

      h1.text-center Gate Configuration
      br
      = f.label :gate_url, "Gate Server URL"
      = f.text_field :gate_url, class: 'form-control', value: @gate_url
      br
      = f.label :gate_token, "Gate Token"
      = f.text_field :gate_token, class: 'form-control', value: @gate_token
      br
      = f.label :min_user_id, "Minimum User ID"
      = f.number_field :min_user_id, class: 'form-control', value: @min_user_id
      br
      = f.label :user_groups, "User Groups"
      = f.text_field :user_groups, class: 'form-control', value: @user_groups
      br
      = f.submit "Apply", class: "btn btn-primary"